string owner
bool active
float32 activation_potential
float32 activation_level
#I don't need the whole status msg but we definitely need the name, active, and activation potential
---
bool success
float32 activation_level